### ISSUE TITLE
how to get base model accuracy

### ISSUE THREAD

**Issue by pursure-D** [pratyushasharma/laser#21]
I should run which command to obtain the accuracy of the base model？

**Comment by dkmisra** [comment]
You can use the flag `--lname dont` to disable performing an intervention. This happens even if `--rate` and `--lnum` values are provided. See the implementation here: 

https://github.com/pratyushasharma/laser/blob/main/src/laser/gptj_laser.py#L94
https://github.com/pratyushasharma/laser/blob/main/src/laser/llama2_laser.py#L100
https://github.com/pratyushasharma/laser/blob/main/src/laser/roberta_laser.py#L45
https://github.com/pratyushasharma/laser/blob/main/src/laser/phi1_5_laser.py#L89
https://github.com/pratyushasharma/laser/blob/main/src/laser/mujoco_dt_laser.py#L40

**Comment by dkmisra** [comment]
Closing this as there has been no further activity. Please feel free to open it, if needed.
