### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [pratyushasharma/laser#3]
Hi,
Great work on this codebase! Would you mind adding a license, ie MIT/Apache/ISC?
Thank you!

**Comment by dkmisra** [comment]
Thanks for the interest :) Please give us 1-3 days to get back on this.

**Comment by fakerybakery** [comment]
Sure. Thank you!

**Comment by fakerybakery** [comment]
Hi, one question: right now, if I use this code without a license, is there currently any restriction on distributing models outputted from this codebase? For example, could I publish it on Hugging Face with a permissive license?
Thank you!

**Comment by Mihaiii** [comment]
> For example, could I publish it on Hugging Face with a permissive license?

It'a not my intention to oversimplify, but if you study the code, you'll see it's not complex. The paper is great because its findings, but from a code perspective, if you're worried about the license, you could just directly use `torch.svd_lowrank`.

**Comment by dkmisra** [comment]
@fakerybakery , we have added MIT license. Let me know if you have any questions or concerns.

@Mihaiii I agree. It should be straightforward to apply LASER from scratch. Most of the code is creating the setup and evaluation.

**Comment by fakerybakery** [comment]
Thank you so much!
