### ISSUE TITLE
Do you think it could work for MoE models like Mixtral? 

### ISSUE THREAD

**Issue by BadisG** [pratyushasharma/laser#7]
Title.

**Comment by dkmisra** [comment]
Possibly. Our results show that LASER does help but there is no mathematical guarantee behind LASER at the moment. Mixtral is 7B which is similar to models we have tried (Llama2-7B and GPT-J 6B) so this is encouraging. Also, we are running on additional LLMs such as LASERs, and folks elsewhere have been trying LASER on other LLMs. We are in the process of doing two things to make this a more engaging exercise for all of us interested:

1. A leaderboard should go live before the end of this week where we will put all results on LASER along with citations of people generating those results.
2. We will release a tutorial (most likely a jupyter notebook) early next week which shows how to use LASER in a new setting, and what we think are important pieces to keep in mind.

In the meantime, we have enabled discussion on this repo. Please feel free to post additional thoughts or questions for brainstorming, which may not be better fit for the issue page.

**Comment by dkmisra** [comment]
I am closing this. This question is more suitable for the discussion page which is now [enabled](https://github.com/pratyushasharma/laser/discussions). Please look at the leaderboard in a week or two. 

If you have more questions, dont hesitate to open a new issue.
